// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"online-teaching/internal/ent/migrate"

	"online-teaching/internal/ent/course"
	"online-teaching/internal/ent/coursechapter"
	"online-teaching/internal/ent/coursecomment"
	"online-teaching/internal/ent/courseinfo"
	"online-teaching/internal/ent/coursesection"
	"online-teaching/internal/ent/courseswiper"
	"online-teaching/internal/ent/teacher"
	"online-teaching/internal/ent/user"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Course is the client for interacting with the Course builders.
	Course *CourseClient
	// CourseChapter is the client for interacting with the CourseChapter builders.
	CourseChapter *CourseChapterClient
	// CourseComment is the client for interacting with the CourseComment builders.
	CourseComment *CourseCommentClient
	// CourseInfo is the client for interacting with the CourseInfo builders.
	CourseInfo *CourseInfoClient
	// CourseSection is the client for interacting with the CourseSection builders.
	CourseSection *CourseSectionClient
	// CourseSwiper is the client for interacting with the CourseSwiper builders.
	CourseSwiper *CourseSwiperClient
	// Teacher is the client for interacting with the Teacher builders.
	Teacher *TeacherClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Course = NewCourseClient(c.config)
	c.CourseChapter = NewCourseChapterClient(c.config)
	c.CourseComment = NewCourseCommentClient(c.config)
	c.CourseInfo = NewCourseInfoClient(c.config)
	c.CourseSection = NewCourseSectionClient(c.config)
	c.CourseSwiper = NewCourseSwiperClient(c.config)
	c.Teacher = NewTeacherClient(c.config)
	c.User = NewUserClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Course:        NewCourseClient(cfg),
		CourseChapter: NewCourseChapterClient(cfg),
		CourseComment: NewCourseCommentClient(cfg),
		CourseInfo:    NewCourseInfoClient(cfg),
		CourseSection: NewCourseSectionClient(cfg),
		CourseSwiper:  NewCourseSwiperClient(cfg),
		Teacher:       NewTeacherClient(cfg),
		User:          NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Course:        NewCourseClient(cfg),
		CourseChapter: NewCourseChapterClient(cfg),
		CourseComment: NewCourseCommentClient(cfg),
		CourseInfo:    NewCourseInfoClient(cfg),
		CourseSection: NewCourseSectionClient(cfg),
		CourseSwiper:  NewCourseSwiperClient(cfg),
		Teacher:       NewTeacherClient(cfg),
		User:          NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Course.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Course.Use(hooks...)
	c.CourseChapter.Use(hooks...)
	c.CourseComment.Use(hooks...)
	c.CourseInfo.Use(hooks...)
	c.CourseSection.Use(hooks...)
	c.CourseSwiper.Use(hooks...)
	c.Teacher.Use(hooks...)
	c.User.Use(hooks...)
}

// CourseClient is a client for the Course schema.
type CourseClient struct {
	config
}

// NewCourseClient returns a client for the Course from the given config.
func NewCourseClient(c config) *CourseClient {
	return &CourseClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `course.Hooks(f(g(h())))`.
func (c *CourseClient) Use(hooks ...Hook) {
	c.hooks.Course = append(c.hooks.Course, hooks...)
}

// Create returns a builder for creating a Course entity.
func (c *CourseClient) Create() *CourseCreate {
	mutation := newCourseMutation(c.config, OpCreate)
	return &CourseCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Course entities.
func (c *CourseClient) CreateBulk(builders ...*CourseCreate) *CourseCreateBulk {
	return &CourseCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Course.
func (c *CourseClient) Update() *CourseUpdate {
	mutation := newCourseMutation(c.config, OpUpdate)
	return &CourseUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CourseClient) UpdateOne(co *Course) *CourseUpdateOne {
	mutation := newCourseMutation(c.config, OpUpdateOne, withCourse(co))
	return &CourseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CourseClient) UpdateOneID(id int) *CourseUpdateOne {
	mutation := newCourseMutation(c.config, OpUpdateOne, withCourseID(id))
	return &CourseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Course.
func (c *CourseClient) Delete() *CourseDelete {
	mutation := newCourseMutation(c.config, OpDelete)
	return &CourseDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CourseClient) DeleteOne(co *Course) *CourseDeleteOne {
	return c.DeleteOneID(co.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *CourseClient) DeleteOneID(id int) *CourseDeleteOne {
	builder := c.Delete().Where(course.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CourseDeleteOne{builder}
}

// Query returns a query builder for Course.
func (c *CourseClient) Query() *CourseQuery {
	return &CourseQuery{
		config: c.config,
	}
}

// Get returns a Course entity by its id.
func (c *CourseClient) Get(ctx context.Context, id int) (*Course, error) {
	return c.Query().Where(course.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CourseClient) GetX(ctx context.Context, id int) *Course {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTeachers queries the teachers edge of a Course.
func (c *CourseClient) QueryTeachers(co *Course) *TeacherQuery {
	query := &TeacherQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := co.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, id),
			sqlgraph.To(teacher.Table, teacher.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, course.TeachersTable, course.TeachersPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(co.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryInfos queries the infos edge of a Course.
func (c *CourseClient) QueryInfos(co *Course) *CourseInfoQuery {
	query := &CourseInfoQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := co.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, id),
			sqlgraph.To(courseinfo.Table, courseinfo.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, course.InfosTable, course.InfosColumn),
		)
		fromV = sqlgraph.Neighbors(co.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChapters queries the chapters edge of a Course.
func (c *CourseClient) QueryChapters(co *Course) *CourseChapterQuery {
	query := &CourseChapterQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := co.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, id),
			sqlgraph.To(coursechapter.Table, coursechapter.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, course.ChaptersTable, course.ChaptersColumn),
		)
		fromV = sqlgraph.Neighbors(co.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySections queries the sections edge of a Course.
func (c *CourseClient) QuerySections(co *Course) *CourseSectionQuery {
	query := &CourseSectionQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := co.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, id),
			sqlgraph.To(coursesection.Table, coursesection.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, course.SectionsTable, course.SectionsColumn),
		)
		fromV = sqlgraph.Neighbors(co.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySwipers queries the swipers edge of a Course.
func (c *CourseClient) QuerySwipers(co *Course) *CourseSwiperQuery {
	query := &CourseSwiperQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := co.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, id),
			sqlgraph.To(courseswiper.Table, courseswiper.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, course.SwipersTable, course.SwipersColumn),
		)
		fromV = sqlgraph.Neighbors(co.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUsers queries the users edge of a Course.
func (c *CourseClient) QueryUsers(co *Course) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := co.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, course.UsersTable, course.UsersPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(co.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CourseClient) Hooks() []Hook {
	return c.hooks.Course
}

// CourseChapterClient is a client for the CourseChapter schema.
type CourseChapterClient struct {
	config
}

// NewCourseChapterClient returns a client for the CourseChapter from the given config.
func NewCourseChapterClient(c config) *CourseChapterClient {
	return &CourseChapterClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `coursechapter.Hooks(f(g(h())))`.
func (c *CourseChapterClient) Use(hooks ...Hook) {
	c.hooks.CourseChapter = append(c.hooks.CourseChapter, hooks...)
}

// Create returns a builder for creating a CourseChapter entity.
func (c *CourseChapterClient) Create() *CourseChapterCreate {
	mutation := newCourseChapterMutation(c.config, OpCreate)
	return &CourseChapterCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CourseChapter entities.
func (c *CourseChapterClient) CreateBulk(builders ...*CourseChapterCreate) *CourseChapterCreateBulk {
	return &CourseChapterCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CourseChapter.
func (c *CourseChapterClient) Update() *CourseChapterUpdate {
	mutation := newCourseChapterMutation(c.config, OpUpdate)
	return &CourseChapterUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CourseChapterClient) UpdateOne(cc *CourseChapter) *CourseChapterUpdateOne {
	mutation := newCourseChapterMutation(c.config, OpUpdateOne, withCourseChapter(cc))
	return &CourseChapterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CourseChapterClient) UpdateOneID(id int) *CourseChapterUpdateOne {
	mutation := newCourseChapterMutation(c.config, OpUpdateOne, withCourseChapterID(id))
	return &CourseChapterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CourseChapter.
func (c *CourseChapterClient) Delete() *CourseChapterDelete {
	mutation := newCourseChapterMutation(c.config, OpDelete)
	return &CourseChapterDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CourseChapterClient) DeleteOne(cc *CourseChapter) *CourseChapterDeleteOne {
	return c.DeleteOneID(cc.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *CourseChapterClient) DeleteOneID(id int) *CourseChapterDeleteOne {
	builder := c.Delete().Where(coursechapter.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CourseChapterDeleteOne{builder}
}

// Query returns a query builder for CourseChapter.
func (c *CourseChapterClient) Query() *CourseChapterQuery {
	return &CourseChapterQuery{
		config: c.config,
	}
}

// Get returns a CourseChapter entity by its id.
func (c *CourseChapterClient) Get(ctx context.Context, id int) (*CourseChapter, error) {
	return c.Query().Where(coursechapter.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CourseChapterClient) GetX(ctx context.Context, id int) *CourseChapter {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCourseSection queries the course_section edge of a CourseChapter.
func (c *CourseChapterClient) QueryCourseSection(cc *CourseChapter) *CourseSectionQuery {
	query := &CourseSectionQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := cc.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(coursechapter.Table, coursechapter.FieldID, id),
			sqlgraph.To(coursesection.Table, coursesection.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, coursechapter.CourseSectionTable, coursechapter.CourseSectionColumn),
		)
		fromV = sqlgraph.Neighbors(cc.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CourseChapterClient) Hooks() []Hook {
	return c.hooks.CourseChapter
}

// CourseCommentClient is a client for the CourseComment schema.
type CourseCommentClient struct {
	config
}

// NewCourseCommentClient returns a client for the CourseComment from the given config.
func NewCourseCommentClient(c config) *CourseCommentClient {
	return &CourseCommentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `coursecomment.Hooks(f(g(h())))`.
func (c *CourseCommentClient) Use(hooks ...Hook) {
	c.hooks.CourseComment = append(c.hooks.CourseComment, hooks...)
}

// Create returns a builder for creating a CourseComment entity.
func (c *CourseCommentClient) Create() *CourseCommentCreate {
	mutation := newCourseCommentMutation(c.config, OpCreate)
	return &CourseCommentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CourseComment entities.
func (c *CourseCommentClient) CreateBulk(builders ...*CourseCommentCreate) *CourseCommentCreateBulk {
	return &CourseCommentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CourseComment.
func (c *CourseCommentClient) Update() *CourseCommentUpdate {
	mutation := newCourseCommentMutation(c.config, OpUpdate)
	return &CourseCommentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CourseCommentClient) UpdateOne(cc *CourseComment) *CourseCommentUpdateOne {
	mutation := newCourseCommentMutation(c.config, OpUpdateOne, withCourseComment(cc))
	return &CourseCommentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CourseCommentClient) UpdateOneID(id int) *CourseCommentUpdateOne {
	mutation := newCourseCommentMutation(c.config, OpUpdateOne, withCourseCommentID(id))
	return &CourseCommentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CourseComment.
func (c *CourseCommentClient) Delete() *CourseCommentDelete {
	mutation := newCourseCommentMutation(c.config, OpDelete)
	return &CourseCommentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CourseCommentClient) DeleteOne(cc *CourseComment) *CourseCommentDeleteOne {
	return c.DeleteOneID(cc.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *CourseCommentClient) DeleteOneID(id int) *CourseCommentDeleteOne {
	builder := c.Delete().Where(coursecomment.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CourseCommentDeleteOne{builder}
}

// Query returns a query builder for CourseComment.
func (c *CourseCommentClient) Query() *CourseCommentQuery {
	return &CourseCommentQuery{
		config: c.config,
	}
}

// Get returns a CourseComment entity by its id.
func (c *CourseCommentClient) Get(ctx context.Context, id int) (*CourseComment, error) {
	return c.Query().Where(coursecomment.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CourseCommentClient) GetX(ctx context.Context, id int) *CourseComment {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CourseCommentClient) Hooks() []Hook {
	return c.hooks.CourseComment
}

// CourseInfoClient is a client for the CourseInfo schema.
type CourseInfoClient struct {
	config
}

// NewCourseInfoClient returns a client for the CourseInfo from the given config.
func NewCourseInfoClient(c config) *CourseInfoClient {
	return &CourseInfoClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `courseinfo.Hooks(f(g(h())))`.
func (c *CourseInfoClient) Use(hooks ...Hook) {
	c.hooks.CourseInfo = append(c.hooks.CourseInfo, hooks...)
}

// Create returns a builder for creating a CourseInfo entity.
func (c *CourseInfoClient) Create() *CourseInfoCreate {
	mutation := newCourseInfoMutation(c.config, OpCreate)
	return &CourseInfoCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CourseInfo entities.
func (c *CourseInfoClient) CreateBulk(builders ...*CourseInfoCreate) *CourseInfoCreateBulk {
	return &CourseInfoCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CourseInfo.
func (c *CourseInfoClient) Update() *CourseInfoUpdate {
	mutation := newCourseInfoMutation(c.config, OpUpdate)
	return &CourseInfoUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CourseInfoClient) UpdateOne(ci *CourseInfo) *CourseInfoUpdateOne {
	mutation := newCourseInfoMutation(c.config, OpUpdateOne, withCourseInfo(ci))
	return &CourseInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CourseInfoClient) UpdateOneID(id int) *CourseInfoUpdateOne {
	mutation := newCourseInfoMutation(c.config, OpUpdateOne, withCourseInfoID(id))
	return &CourseInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CourseInfo.
func (c *CourseInfoClient) Delete() *CourseInfoDelete {
	mutation := newCourseInfoMutation(c.config, OpDelete)
	return &CourseInfoDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CourseInfoClient) DeleteOne(ci *CourseInfo) *CourseInfoDeleteOne {
	return c.DeleteOneID(ci.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *CourseInfoClient) DeleteOneID(id int) *CourseInfoDeleteOne {
	builder := c.Delete().Where(courseinfo.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CourseInfoDeleteOne{builder}
}

// Query returns a query builder for CourseInfo.
func (c *CourseInfoClient) Query() *CourseInfoQuery {
	return &CourseInfoQuery{
		config: c.config,
	}
}

// Get returns a CourseInfo entity by its id.
func (c *CourseInfoClient) Get(ctx context.Context, id int) (*CourseInfo, error) {
	return c.Query().Where(courseinfo.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CourseInfoClient) GetX(ctx context.Context, id int) *CourseInfo {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CourseInfoClient) Hooks() []Hook {
	return c.hooks.CourseInfo
}

// CourseSectionClient is a client for the CourseSection schema.
type CourseSectionClient struct {
	config
}

// NewCourseSectionClient returns a client for the CourseSection from the given config.
func NewCourseSectionClient(c config) *CourseSectionClient {
	return &CourseSectionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `coursesection.Hooks(f(g(h())))`.
func (c *CourseSectionClient) Use(hooks ...Hook) {
	c.hooks.CourseSection = append(c.hooks.CourseSection, hooks...)
}

// Create returns a builder for creating a CourseSection entity.
func (c *CourseSectionClient) Create() *CourseSectionCreate {
	mutation := newCourseSectionMutation(c.config, OpCreate)
	return &CourseSectionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CourseSection entities.
func (c *CourseSectionClient) CreateBulk(builders ...*CourseSectionCreate) *CourseSectionCreateBulk {
	return &CourseSectionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CourseSection.
func (c *CourseSectionClient) Update() *CourseSectionUpdate {
	mutation := newCourseSectionMutation(c.config, OpUpdate)
	return &CourseSectionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CourseSectionClient) UpdateOne(cs *CourseSection) *CourseSectionUpdateOne {
	mutation := newCourseSectionMutation(c.config, OpUpdateOne, withCourseSection(cs))
	return &CourseSectionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CourseSectionClient) UpdateOneID(id int) *CourseSectionUpdateOne {
	mutation := newCourseSectionMutation(c.config, OpUpdateOne, withCourseSectionID(id))
	return &CourseSectionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CourseSection.
func (c *CourseSectionClient) Delete() *CourseSectionDelete {
	mutation := newCourseSectionMutation(c.config, OpDelete)
	return &CourseSectionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CourseSectionClient) DeleteOne(cs *CourseSection) *CourseSectionDeleteOne {
	return c.DeleteOneID(cs.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *CourseSectionClient) DeleteOneID(id int) *CourseSectionDeleteOne {
	builder := c.Delete().Where(coursesection.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CourseSectionDeleteOne{builder}
}

// Query returns a query builder for CourseSection.
func (c *CourseSectionClient) Query() *CourseSectionQuery {
	return &CourseSectionQuery{
		config: c.config,
	}
}

// Get returns a CourseSection entity by its id.
func (c *CourseSectionClient) Get(ctx context.Context, id int) (*CourseSection, error) {
	return c.Query().Where(coursesection.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CourseSectionClient) GetX(ctx context.Context, id int) *CourseSection {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CourseSectionClient) Hooks() []Hook {
	return c.hooks.CourseSection
}

// CourseSwiperClient is a client for the CourseSwiper schema.
type CourseSwiperClient struct {
	config
}

// NewCourseSwiperClient returns a client for the CourseSwiper from the given config.
func NewCourseSwiperClient(c config) *CourseSwiperClient {
	return &CourseSwiperClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `courseswiper.Hooks(f(g(h())))`.
func (c *CourseSwiperClient) Use(hooks ...Hook) {
	c.hooks.CourseSwiper = append(c.hooks.CourseSwiper, hooks...)
}

// Create returns a builder for creating a CourseSwiper entity.
func (c *CourseSwiperClient) Create() *CourseSwiperCreate {
	mutation := newCourseSwiperMutation(c.config, OpCreate)
	return &CourseSwiperCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CourseSwiper entities.
func (c *CourseSwiperClient) CreateBulk(builders ...*CourseSwiperCreate) *CourseSwiperCreateBulk {
	return &CourseSwiperCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CourseSwiper.
func (c *CourseSwiperClient) Update() *CourseSwiperUpdate {
	mutation := newCourseSwiperMutation(c.config, OpUpdate)
	return &CourseSwiperUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CourseSwiperClient) UpdateOne(cs *CourseSwiper) *CourseSwiperUpdateOne {
	mutation := newCourseSwiperMutation(c.config, OpUpdateOne, withCourseSwiper(cs))
	return &CourseSwiperUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CourseSwiperClient) UpdateOneID(id int) *CourseSwiperUpdateOne {
	mutation := newCourseSwiperMutation(c.config, OpUpdateOne, withCourseSwiperID(id))
	return &CourseSwiperUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CourseSwiper.
func (c *CourseSwiperClient) Delete() *CourseSwiperDelete {
	mutation := newCourseSwiperMutation(c.config, OpDelete)
	return &CourseSwiperDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CourseSwiperClient) DeleteOne(cs *CourseSwiper) *CourseSwiperDeleteOne {
	return c.DeleteOneID(cs.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *CourseSwiperClient) DeleteOneID(id int) *CourseSwiperDeleteOne {
	builder := c.Delete().Where(courseswiper.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CourseSwiperDeleteOne{builder}
}

// Query returns a query builder for CourseSwiper.
func (c *CourseSwiperClient) Query() *CourseSwiperQuery {
	return &CourseSwiperQuery{
		config: c.config,
	}
}

// Get returns a CourseSwiper entity by its id.
func (c *CourseSwiperClient) Get(ctx context.Context, id int) (*CourseSwiper, error) {
	return c.Query().Where(courseswiper.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CourseSwiperClient) GetX(ctx context.Context, id int) *CourseSwiper {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CourseSwiperClient) Hooks() []Hook {
	return c.hooks.CourseSwiper
}

// TeacherClient is a client for the Teacher schema.
type TeacherClient struct {
	config
}

// NewTeacherClient returns a client for the Teacher from the given config.
func NewTeacherClient(c config) *TeacherClient {
	return &TeacherClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `teacher.Hooks(f(g(h())))`.
func (c *TeacherClient) Use(hooks ...Hook) {
	c.hooks.Teacher = append(c.hooks.Teacher, hooks...)
}

// Create returns a builder for creating a Teacher entity.
func (c *TeacherClient) Create() *TeacherCreate {
	mutation := newTeacherMutation(c.config, OpCreate)
	return &TeacherCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Teacher entities.
func (c *TeacherClient) CreateBulk(builders ...*TeacherCreate) *TeacherCreateBulk {
	return &TeacherCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Teacher.
func (c *TeacherClient) Update() *TeacherUpdate {
	mutation := newTeacherMutation(c.config, OpUpdate)
	return &TeacherUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TeacherClient) UpdateOne(t *Teacher) *TeacherUpdateOne {
	mutation := newTeacherMutation(c.config, OpUpdateOne, withTeacher(t))
	return &TeacherUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TeacherClient) UpdateOneID(id int) *TeacherUpdateOne {
	mutation := newTeacherMutation(c.config, OpUpdateOne, withTeacherID(id))
	return &TeacherUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Teacher.
func (c *TeacherClient) Delete() *TeacherDelete {
	mutation := newTeacherMutation(c.config, OpDelete)
	return &TeacherDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TeacherClient) DeleteOne(t *Teacher) *TeacherDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *TeacherClient) DeleteOneID(id int) *TeacherDeleteOne {
	builder := c.Delete().Where(teacher.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TeacherDeleteOne{builder}
}

// Query returns a query builder for Teacher.
func (c *TeacherClient) Query() *TeacherQuery {
	return &TeacherQuery{
		config: c.config,
	}
}

// Get returns a Teacher entity by its id.
func (c *TeacherClient) Get(ctx context.Context, id int) (*Teacher, error) {
	return c.Query().Where(teacher.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TeacherClient) GetX(ctx context.Context, id int) *Teacher {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCourses queries the courses edge of a Teacher.
func (c *TeacherClient) QueryCourses(t *Teacher) *CourseQuery {
	query := &CourseQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(teacher.Table, teacher.FieldID, id),
			sqlgraph.To(course.Table, course.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, teacher.CoursesTable, teacher.CoursesPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TeacherClient) Hooks() []Hook {
	return c.hooks.Teacher
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCourses queries the courses edge of a User.
func (c *UserClient) QueryCourses(u *User) *CourseQuery {
	query := &CourseQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(course.Table, course.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, user.CoursesTable, user.CoursesPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}
