// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"online-teaching/internal/ent/course"
	"online-teaching/internal/ent/coursechapter"
	"online-teaching/internal/ent/courseinfo"
	"online-teaching/internal/ent/coursesection"
	"online-teaching/internal/ent/courseteacher"
	"online-teaching/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CourseQuery is the builder for querying Course entities.
type CourseQuery struct {
	config
	limit             *int
	offset            *int
	unique            *bool
	order             []OrderFunc
	fields            []string
	predicates        []predicate.Course
	withCourseTeacher *CourseTeacherQuery
	withCourseInfo    *CourseInfoQuery
	withCourseChapter *CourseChapterQuery
	withCourseSection *CourseSectionQuery
	withFKs           bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CourseQuery builder.
func (cq *CourseQuery) Where(ps ...predicate.Course) *CourseQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit adds a limit step to the query.
func (cq *CourseQuery) Limit(limit int) *CourseQuery {
	cq.limit = &limit
	return cq
}

// Offset adds an offset step to the query.
func (cq *CourseQuery) Offset(offset int) *CourseQuery {
	cq.offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *CourseQuery) Unique(unique bool) *CourseQuery {
	cq.unique = &unique
	return cq
}

// Order adds an order step to the query.
func (cq *CourseQuery) Order(o ...OrderFunc) *CourseQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QueryCourseTeacher chains the current query on the "course_teacher" edge.
func (cq *CourseQuery) QueryCourseTeacher() *CourseTeacherQuery {
	query := &CourseTeacherQuery{config: cq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, selector),
			sqlgraph.To(courseteacher.Table, courseteacher.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, course.CourseTeacherTable, course.CourseTeacherColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCourseInfo chains the current query on the "course_info" edge.
func (cq *CourseQuery) QueryCourseInfo() *CourseInfoQuery {
	query := &CourseInfoQuery{config: cq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, selector),
			sqlgraph.To(courseinfo.Table, courseinfo.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, course.CourseInfoTable, course.CourseInfoColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCourseChapter chains the current query on the "course_chapter" edge.
func (cq *CourseQuery) QueryCourseChapter() *CourseChapterQuery {
	query := &CourseChapterQuery{config: cq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, selector),
			sqlgraph.To(coursechapter.Table, coursechapter.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, course.CourseChapterTable, course.CourseChapterColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCourseSection chains the current query on the "course_section" edge.
func (cq *CourseQuery) QueryCourseSection() *CourseSectionQuery {
	query := &CourseSectionQuery{config: cq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, selector),
			sqlgraph.To(coursesection.Table, coursesection.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, course.CourseSectionTable, course.CourseSectionColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Course entity from the query.
// Returns a *NotFoundError when no Course was found.
func (cq *CourseQuery) First(ctx context.Context) (*Course, error) {
	nodes, err := cq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{course.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *CourseQuery) FirstX(ctx context.Context) *Course {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Course ID from the query.
// Returns a *NotFoundError when no Course ID was found.
func (cq *CourseQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{course.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *CourseQuery) FirstIDX(ctx context.Context) int {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Course entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Course entity is found.
// Returns a *NotFoundError when no Course entities are found.
func (cq *CourseQuery) Only(ctx context.Context) (*Course, error) {
	nodes, err := cq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{course.Label}
	default:
		return nil, &NotSingularError{course.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *CourseQuery) OnlyX(ctx context.Context) *Course {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Course ID in the query.
// Returns a *NotSingularError when more than one Course ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *CourseQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{course.Label}
	default:
		err = &NotSingularError{course.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *CourseQuery) OnlyIDX(ctx context.Context) int {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Courses.
func (cq *CourseQuery) All(ctx context.Context) ([]*Course, error) {
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return cq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (cq *CourseQuery) AllX(ctx context.Context) []*Course {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Course IDs.
func (cq *CourseQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := cq.Select(course.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *CourseQuery) IDsX(ctx context.Context) []int {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *CourseQuery) Count(ctx context.Context) (int, error) {
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return cq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (cq *CourseQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *CourseQuery) Exist(ctx context.Context) (bool, error) {
	if err := cq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return cq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *CourseQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CourseQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *CourseQuery) Clone() *CourseQuery {
	if cq == nil {
		return nil
	}
	return &CourseQuery{
		config:            cq.config,
		limit:             cq.limit,
		offset:            cq.offset,
		order:             append([]OrderFunc{}, cq.order...),
		predicates:        append([]predicate.Course{}, cq.predicates...),
		withCourseTeacher: cq.withCourseTeacher.Clone(),
		withCourseInfo:    cq.withCourseInfo.Clone(),
		withCourseChapter: cq.withCourseChapter.Clone(),
		withCourseSection: cq.withCourseSection.Clone(),
		// clone intermediate query.
		sql:    cq.sql.Clone(),
		path:   cq.path,
		unique: cq.unique,
	}
}

// WithCourseTeacher tells the query-builder to eager-load the nodes that are connected to
// the "course_teacher" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CourseQuery) WithCourseTeacher(opts ...func(*CourseTeacherQuery)) *CourseQuery {
	query := &CourseTeacherQuery{config: cq.config}
	for _, opt := range opts {
		opt(query)
	}
	cq.withCourseTeacher = query
	return cq
}

// WithCourseInfo tells the query-builder to eager-load the nodes that are connected to
// the "course_info" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CourseQuery) WithCourseInfo(opts ...func(*CourseInfoQuery)) *CourseQuery {
	query := &CourseInfoQuery{config: cq.config}
	for _, opt := range opts {
		opt(query)
	}
	cq.withCourseInfo = query
	return cq
}

// WithCourseChapter tells the query-builder to eager-load the nodes that are connected to
// the "course_chapter" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CourseQuery) WithCourseChapter(opts ...func(*CourseChapterQuery)) *CourseQuery {
	query := &CourseChapterQuery{config: cq.config}
	for _, opt := range opts {
		opt(query)
	}
	cq.withCourseChapter = query
	return cq
}

// WithCourseSection tells the query-builder to eager-load the nodes that are connected to
// the "course_section" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CourseQuery) WithCourseSection(opts ...func(*CourseSectionQuery)) *CourseQuery {
	query := &CourseSectionQuery{config: cq.config}
	for _, opt := range opts {
		opt(query)
	}
	cq.withCourseSection = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Course.Query().
//		GroupBy(course.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (cq *CourseQuery) GroupBy(field string, fields ...string) *CourseGroupBy {
	grbuild := &CourseGroupBy{config: cq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return cq.sqlQuery(ctx), nil
	}
	grbuild.label = course.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Course.Query().
//		Select(course.FieldName).
//		Scan(ctx, &v)
//
func (cq *CourseQuery) Select(fields ...string) *CourseSelect {
	cq.fields = append(cq.fields, fields...)
	selbuild := &CourseSelect{CourseQuery: cq}
	selbuild.label = course.Label
	selbuild.flds, selbuild.scan = &cq.fields, selbuild.Scan
	return selbuild
}

func (cq *CourseQuery) prepareQuery(ctx context.Context) error {
	for _, f := range cq.fields {
		if !course.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *CourseQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Course, error) {
	var (
		nodes       = []*Course{}
		withFKs     = cq.withFKs
		_spec       = cq.querySpec()
		loadedTypes = [4]bool{
			cq.withCourseTeacher != nil,
			cq.withCourseInfo != nil,
			cq.withCourseChapter != nil,
			cq.withCourseSection != nil,
		}
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, course.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*Course).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &Course{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withCourseTeacher; query != nil {
		if err := cq.loadCourseTeacher(ctx, query, nodes,
			func(n *Course) { n.Edges.CourseTeacher = []*CourseTeacher{} },
			func(n *Course, e *CourseTeacher) { n.Edges.CourseTeacher = append(n.Edges.CourseTeacher, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withCourseInfo; query != nil {
		if err := cq.loadCourseInfo(ctx, query, nodes,
			func(n *Course) { n.Edges.CourseInfo = []*CourseInfo{} },
			func(n *Course, e *CourseInfo) { n.Edges.CourseInfo = append(n.Edges.CourseInfo, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withCourseChapter; query != nil {
		if err := cq.loadCourseChapter(ctx, query, nodes,
			func(n *Course) { n.Edges.CourseChapter = []*CourseChapter{} },
			func(n *Course, e *CourseChapter) { n.Edges.CourseChapter = append(n.Edges.CourseChapter, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withCourseSection; query != nil {
		if err := cq.loadCourseSection(ctx, query, nodes,
			func(n *Course) { n.Edges.CourseSection = []*CourseSection{} },
			func(n *Course, e *CourseSection) { n.Edges.CourseSection = append(n.Edges.CourseSection, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *CourseQuery) loadCourseTeacher(ctx context.Context, query *CourseTeacherQuery, nodes []*Course, init func(*Course), assign func(*Course, *CourseTeacher)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Course)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.CourseTeacher(func(s *sql.Selector) {
		s.Where(sql.InValues(course.CourseTeacherColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.course_course_teacher
		if fk == nil {
			return fmt.Errorf(`foreign-key "course_course_teacher" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "course_course_teacher" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (cq *CourseQuery) loadCourseInfo(ctx context.Context, query *CourseInfoQuery, nodes []*Course, init func(*Course), assign func(*Course, *CourseInfo)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Course)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.CourseInfo(func(s *sql.Selector) {
		s.Where(sql.InValues(course.CourseInfoColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.course_course_info
		if fk == nil {
			return fmt.Errorf(`foreign-key "course_course_info" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "course_course_info" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (cq *CourseQuery) loadCourseChapter(ctx context.Context, query *CourseChapterQuery, nodes []*Course, init func(*Course), assign func(*Course, *CourseChapter)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Course)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.CourseChapter(func(s *sql.Selector) {
		s.Where(sql.InValues(course.CourseChapterColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.course_course_chapter
		if fk == nil {
			return fmt.Errorf(`foreign-key "course_course_chapter" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "course_course_chapter" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (cq *CourseQuery) loadCourseSection(ctx context.Context, query *CourseSectionQuery, nodes []*Course, init func(*Course), assign func(*Course, *CourseSection)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Course)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.CourseSection(func(s *sql.Selector) {
		s.Where(sql.InValues(course.CourseSectionColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.course_course_section
		if fk == nil {
			return fmt.Errorf(`foreign-key "course_course_section" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "course_course_section" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cq *CourseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	_spec.Node.Columns = cq.fields
	if len(cq.fields) > 0 {
		_spec.Unique = cq.unique != nil && *cq.unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *CourseQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := cq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (cq *CourseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   course.Table,
			Columns: course.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: course.FieldID,
			},
		},
		From:   cq.sql,
		Unique: true,
	}
	if unique := cq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := cq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, course.FieldID)
		for i := range fields {
			if fields[i] != course.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *CourseQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(course.Table)
	columns := cq.fields
	if len(columns) == 0 {
		columns = course.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.unique != nil && *cq.unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CourseGroupBy is the group-by builder for Course entities.
type CourseGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *CourseGroupBy) Aggregate(fns ...AggregateFunc) *CourseGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the group-by query and scans the result into the given value.
func (cgb *CourseGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := cgb.path(ctx)
	if err != nil {
		return err
	}
	cgb.sql = query
	return cgb.sqlScan(ctx, v)
}

func (cgb *CourseGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range cgb.fields {
		if !course.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := cgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (cgb *CourseGroupBy) sqlQuery() *sql.Selector {
	selector := cgb.sql.Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(cgb.fields)+len(cgb.fns))
		for _, f := range cgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(cgb.fields...)...)
}

// CourseSelect is the builder for selecting fields of Course entities.
type CourseSelect struct {
	*CourseQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (cs *CourseSelect) Scan(ctx context.Context, v interface{}) error {
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	cs.sql = cs.CourseQuery.sqlQuery(ctx)
	return cs.sqlScan(ctx, v)
}

func (cs *CourseSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := cs.sql.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
