// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"online-teaching/internal/ent/coursechapter"
	"online-teaching/internal/ent/coursesection"
	"online-teaching/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CourseChapterQuery is the builder for querying CourseChapter entities.
type CourseChapterQuery struct {
	config
	limit             *int
	offset            *int
	unique            *bool
	order             []OrderFunc
	fields            []string
	predicates        []predicate.CourseChapter
	withCourseSection *CourseSectionQuery
	withFKs           bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CourseChapterQuery builder.
func (ccq *CourseChapterQuery) Where(ps ...predicate.CourseChapter) *CourseChapterQuery {
	ccq.predicates = append(ccq.predicates, ps...)
	return ccq
}

// Limit adds a limit step to the query.
func (ccq *CourseChapterQuery) Limit(limit int) *CourseChapterQuery {
	ccq.limit = &limit
	return ccq
}

// Offset adds an offset step to the query.
func (ccq *CourseChapterQuery) Offset(offset int) *CourseChapterQuery {
	ccq.offset = &offset
	return ccq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ccq *CourseChapterQuery) Unique(unique bool) *CourseChapterQuery {
	ccq.unique = &unique
	return ccq
}

// Order adds an order step to the query.
func (ccq *CourseChapterQuery) Order(o ...OrderFunc) *CourseChapterQuery {
	ccq.order = append(ccq.order, o...)
	return ccq
}

// QueryCourseSection chains the current query on the "course_section" edge.
func (ccq *CourseChapterQuery) QueryCourseSection() *CourseSectionQuery {
	query := &CourseSectionQuery{config: ccq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ccq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ccq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(coursechapter.Table, coursechapter.FieldID, selector),
			sqlgraph.To(coursesection.Table, coursesection.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, coursechapter.CourseSectionTable, coursechapter.CourseSectionColumn),
		)
		fromU = sqlgraph.SetNeighbors(ccq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CourseChapter entity from the query.
// Returns a *NotFoundError when no CourseChapter was found.
func (ccq *CourseChapterQuery) First(ctx context.Context) (*CourseChapter, error) {
	nodes, err := ccq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{coursechapter.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ccq *CourseChapterQuery) FirstX(ctx context.Context) *CourseChapter {
	node, err := ccq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CourseChapter ID from the query.
// Returns a *NotFoundError when no CourseChapter ID was found.
func (ccq *CourseChapterQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ccq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{coursechapter.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ccq *CourseChapterQuery) FirstIDX(ctx context.Context) int {
	id, err := ccq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CourseChapter entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CourseChapter entity is found.
// Returns a *NotFoundError when no CourseChapter entities are found.
func (ccq *CourseChapterQuery) Only(ctx context.Context) (*CourseChapter, error) {
	nodes, err := ccq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{coursechapter.Label}
	default:
		return nil, &NotSingularError{coursechapter.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ccq *CourseChapterQuery) OnlyX(ctx context.Context) *CourseChapter {
	node, err := ccq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CourseChapter ID in the query.
// Returns a *NotSingularError when more than one CourseChapter ID is found.
// Returns a *NotFoundError when no entities are found.
func (ccq *CourseChapterQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ccq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{coursechapter.Label}
	default:
		err = &NotSingularError{coursechapter.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ccq *CourseChapterQuery) OnlyIDX(ctx context.Context) int {
	id, err := ccq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CourseChapters.
func (ccq *CourseChapterQuery) All(ctx context.Context) ([]*CourseChapter, error) {
	if err := ccq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ccq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ccq *CourseChapterQuery) AllX(ctx context.Context) []*CourseChapter {
	nodes, err := ccq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CourseChapter IDs.
func (ccq *CourseChapterQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ccq.Select(coursechapter.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ccq *CourseChapterQuery) IDsX(ctx context.Context) []int {
	ids, err := ccq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ccq *CourseChapterQuery) Count(ctx context.Context) (int, error) {
	if err := ccq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ccq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ccq *CourseChapterQuery) CountX(ctx context.Context) int {
	count, err := ccq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ccq *CourseChapterQuery) Exist(ctx context.Context) (bool, error) {
	if err := ccq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ccq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ccq *CourseChapterQuery) ExistX(ctx context.Context) bool {
	exist, err := ccq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CourseChapterQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ccq *CourseChapterQuery) Clone() *CourseChapterQuery {
	if ccq == nil {
		return nil
	}
	return &CourseChapterQuery{
		config:            ccq.config,
		limit:             ccq.limit,
		offset:            ccq.offset,
		order:             append([]OrderFunc{}, ccq.order...),
		predicates:        append([]predicate.CourseChapter{}, ccq.predicates...),
		withCourseSection: ccq.withCourseSection.Clone(),
		// clone intermediate query.
		sql:    ccq.sql.Clone(),
		path:   ccq.path,
		unique: ccq.unique,
	}
}

// WithCourseSection tells the query-builder to eager-load the nodes that are connected to
// the "course_section" edge. The optional arguments are used to configure the query builder of the edge.
func (ccq *CourseChapterQuery) WithCourseSection(opts ...func(*CourseSectionQuery)) *CourseChapterQuery {
	query := &CourseSectionQuery{config: ccq.config}
	for _, opt := range opts {
		opt(query)
	}
	ccq.withCourseSection = query
	return ccq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CourseChapter.Query().
//		GroupBy(coursechapter.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ccq *CourseChapterQuery) GroupBy(field string, fields ...string) *CourseChapterGroupBy {
	grbuild := &CourseChapterGroupBy{config: ccq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ccq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ccq.sqlQuery(ctx), nil
	}
	grbuild.label = coursechapter.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.CourseChapter.Query().
//		Select(coursechapter.FieldTitle).
//		Scan(ctx, &v)
//
func (ccq *CourseChapterQuery) Select(fields ...string) *CourseChapterSelect {
	ccq.fields = append(ccq.fields, fields...)
	selbuild := &CourseChapterSelect{CourseChapterQuery: ccq}
	selbuild.label = coursechapter.Label
	selbuild.flds, selbuild.scan = &ccq.fields, selbuild.Scan
	return selbuild
}

func (ccq *CourseChapterQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ccq.fields {
		if !coursechapter.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ccq.path != nil {
		prev, err := ccq.path(ctx)
		if err != nil {
			return err
		}
		ccq.sql = prev
	}
	return nil
}

func (ccq *CourseChapterQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CourseChapter, error) {
	var (
		nodes       = []*CourseChapter{}
		withFKs     = ccq.withFKs
		_spec       = ccq.querySpec()
		loadedTypes = [1]bool{
			ccq.withCourseSection != nil,
		}
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, coursechapter.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*CourseChapter).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &CourseChapter{config: ccq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ccq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ccq.withCourseSection; query != nil {
		if err := ccq.loadCourseSection(ctx, query, nodes,
			func(n *CourseChapter) { n.Edges.CourseSection = []*CourseSection{} },
			func(n *CourseChapter, e *CourseSection) { n.Edges.CourseSection = append(n.Edges.CourseSection, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ccq *CourseChapterQuery) loadCourseSection(ctx context.Context, query *CourseSectionQuery, nodes []*CourseChapter, init func(*CourseChapter), assign func(*CourseChapter, *CourseSection)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*CourseChapter)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.CourseSection(func(s *sql.Selector) {
		s.Where(sql.InValues(coursechapter.CourseSectionColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.course_chapter_course_section
		if fk == nil {
			return fmt.Errorf(`foreign-key "course_chapter_course_section" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "course_chapter_course_section" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (ccq *CourseChapterQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ccq.querySpec()
	_spec.Node.Columns = ccq.fields
	if len(ccq.fields) > 0 {
		_spec.Unique = ccq.unique != nil && *ccq.unique
	}
	return sqlgraph.CountNodes(ctx, ccq.driver, _spec)
}

func (ccq *CourseChapterQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ccq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ccq *CourseChapterQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   coursechapter.Table,
			Columns: coursechapter.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: coursechapter.FieldID,
			},
		},
		From:   ccq.sql,
		Unique: true,
	}
	if unique := ccq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ccq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, coursechapter.FieldID)
		for i := range fields {
			if fields[i] != coursechapter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ccq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ccq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ccq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ccq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ccq *CourseChapterQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ccq.driver.Dialect())
	t1 := builder.Table(coursechapter.Table)
	columns := ccq.fields
	if len(columns) == 0 {
		columns = coursechapter.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ccq.sql != nil {
		selector = ccq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ccq.unique != nil && *ccq.unique {
		selector.Distinct()
	}
	for _, p := range ccq.predicates {
		p(selector)
	}
	for _, p := range ccq.order {
		p(selector)
	}
	if offset := ccq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ccq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CourseChapterGroupBy is the group-by builder for CourseChapter entities.
type CourseChapterGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ccgb *CourseChapterGroupBy) Aggregate(fns ...AggregateFunc) *CourseChapterGroupBy {
	ccgb.fns = append(ccgb.fns, fns...)
	return ccgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ccgb *CourseChapterGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ccgb.path(ctx)
	if err != nil {
		return err
	}
	ccgb.sql = query
	return ccgb.sqlScan(ctx, v)
}

func (ccgb *CourseChapterGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ccgb.fields {
		if !coursechapter.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ccgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ccgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ccgb *CourseChapterGroupBy) sqlQuery() *sql.Selector {
	selector := ccgb.sql.Select()
	aggregation := make([]string, 0, len(ccgb.fns))
	for _, fn := range ccgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ccgb.fields)+len(ccgb.fns))
		for _, f := range ccgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ccgb.fields...)...)
}

// CourseChapterSelect is the builder for selecting fields of CourseChapter entities.
type CourseChapterSelect struct {
	*CourseChapterQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ccs *CourseChapterSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ccs.prepareQuery(ctx); err != nil {
		return err
	}
	ccs.sql = ccs.CourseChapterQuery.sqlQuery(ctx)
	return ccs.sqlScan(ctx, v)
}

func (ccs *CourseChapterSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ccs.sql.Query()
	if err := ccs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
