// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"online-teaching/internal/ent/course"
	"online-teaching/internal/ent/courseteacher"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CourseTeacherCreate is the builder for creating a CourseTeacher entity.
type CourseTeacherCreate struct {
	config
	mutation *CourseTeacherMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (ctc *CourseTeacherCreate) SetName(s string) *CourseTeacherCreate {
	ctc.mutation.SetName(s)
	return ctc
}

// SetDesc sets the "desc" field.
func (ctc *CourseTeacherCreate) SetDesc(s string) *CourseTeacherCreate {
	ctc.mutation.SetDesc(s)
	return ctc
}

// SetAvatar sets the "avatar" field.
func (ctc *CourseTeacherCreate) SetAvatar(s string) *CourseTeacherCreate {
	ctc.mutation.SetAvatar(s)
	return ctc
}

// SetTitle sets the "title" field.
func (ctc *CourseTeacherCreate) SetTitle(s string) *CourseTeacherCreate {
	ctc.mutation.SetTitle(s)
	return ctc
}

// SetIsDeleted sets the "is_deleted" field.
func (ctc *CourseTeacherCreate) SetIsDeleted(b bool) *CourseTeacherCreate {
	ctc.mutation.SetIsDeleted(b)
	return ctc
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (ctc *CourseTeacherCreate) SetNillableIsDeleted(b *bool) *CourseTeacherCreate {
	if b != nil {
		ctc.SetIsDeleted(*b)
	}
	return ctc
}

// SetCreatedAt sets the "created_at" field.
func (ctc *CourseTeacherCreate) SetCreatedAt(t time.Time) *CourseTeacherCreate {
	ctc.mutation.SetCreatedAt(t)
	return ctc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ctc *CourseTeacherCreate) SetNillableCreatedAt(t *time.Time) *CourseTeacherCreate {
	if t != nil {
		ctc.SetCreatedAt(*t)
	}
	return ctc
}

// SetUpdatedAt sets the "updated_at" field.
func (ctc *CourseTeacherCreate) SetUpdatedAt(t time.Time) *CourseTeacherCreate {
	ctc.mutation.SetUpdatedAt(t)
	return ctc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ctc *CourseTeacherCreate) SetNillableUpdatedAt(t *time.Time) *CourseTeacherCreate {
	if t != nil {
		ctc.SetUpdatedAt(*t)
	}
	return ctc
}

// SetDeletedAt sets the "deleted_at" field.
func (ctc *CourseTeacherCreate) SetDeletedAt(t time.Time) *CourseTeacherCreate {
	ctc.mutation.SetDeletedAt(t)
	return ctc
}

// AddCourseIDs adds the "course" edge to the Course entity by IDs.
func (ctc *CourseTeacherCreate) AddCourseIDs(ids ...int) *CourseTeacherCreate {
	ctc.mutation.AddCourseIDs(ids...)
	return ctc
}

// AddCourse adds the "course" edges to the Course entity.
func (ctc *CourseTeacherCreate) AddCourse(c ...*Course) *CourseTeacherCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ctc.AddCourseIDs(ids...)
}

// Mutation returns the CourseTeacherMutation object of the builder.
func (ctc *CourseTeacherCreate) Mutation() *CourseTeacherMutation {
	return ctc.mutation
}

// Save creates the CourseTeacher in the database.
func (ctc *CourseTeacherCreate) Save(ctx context.Context) (*CourseTeacher, error) {
	var (
		err  error
		node *CourseTeacher
	)
	ctc.defaults()
	if len(ctc.hooks) == 0 {
		if err = ctc.check(); err != nil {
			return nil, err
		}
		node, err = ctc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CourseTeacherMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ctc.check(); err != nil {
				return nil, err
			}
			ctc.mutation = mutation
			if node, err = ctc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ctc.hooks) - 1; i >= 0; i-- {
			if ctc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ctc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ctc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*CourseTeacher)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from CourseTeacherMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ctc *CourseTeacherCreate) SaveX(ctx context.Context) *CourseTeacher {
	v, err := ctc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ctc *CourseTeacherCreate) Exec(ctx context.Context) error {
	_, err := ctc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ctc *CourseTeacherCreate) ExecX(ctx context.Context) {
	if err := ctc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ctc *CourseTeacherCreate) defaults() {
	if _, ok := ctc.mutation.IsDeleted(); !ok {
		v := courseteacher.DefaultIsDeleted
		ctc.mutation.SetIsDeleted(v)
	}
	if _, ok := ctc.mutation.CreatedAt(); !ok {
		v := courseteacher.DefaultCreatedAt()
		ctc.mutation.SetCreatedAt(v)
	}
	if _, ok := ctc.mutation.UpdatedAt(); !ok {
		v := courseteacher.DefaultUpdatedAt()
		ctc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ctc *CourseTeacherCreate) check() error {
	if _, ok := ctc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CourseTeacher.name"`)}
	}
	if v, ok := ctc.mutation.Name(); ok {
		if err := courseteacher.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CourseTeacher.name": %w`, err)}
		}
	}
	if _, ok := ctc.mutation.Desc(); !ok {
		return &ValidationError{Name: "desc", err: errors.New(`ent: missing required field "CourseTeacher.desc"`)}
	}
	if _, ok := ctc.mutation.Avatar(); !ok {
		return &ValidationError{Name: "avatar", err: errors.New(`ent: missing required field "CourseTeacher.avatar"`)}
	}
	if _, ok := ctc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "CourseTeacher.title"`)}
	}
	if _, ok := ctc.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New(`ent: missing required field "CourseTeacher.is_deleted"`)}
	}
	if _, ok := ctc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CourseTeacher.created_at"`)}
	}
	if _, ok := ctc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CourseTeacher.updated_at"`)}
	}
	if _, ok := ctc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "CourseTeacher.deleted_at"`)}
	}
	return nil
}

func (ctc *CourseTeacherCreate) sqlSave(ctx context.Context) (*CourseTeacher, error) {
	_node, _spec := ctc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ctc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ctc *CourseTeacherCreate) createSpec() (*CourseTeacher, *sqlgraph.CreateSpec) {
	var (
		_node = &CourseTeacher{config: ctc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: courseteacher.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: courseteacher.FieldID,
			},
		}
	)
	if value, ok := ctc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: courseteacher.FieldName,
		})
		_node.Name = value
	}
	if value, ok := ctc.mutation.Desc(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: courseteacher.FieldDesc,
		})
		_node.Desc = value
	}
	if value, ok := ctc.mutation.Avatar(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: courseteacher.FieldAvatar,
		})
		_node.Avatar = value
	}
	if value, ok := ctc.mutation.Title(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: courseteacher.FieldTitle,
		})
		_node.Title = value
	}
	if value, ok := ctc.mutation.IsDeleted(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: courseteacher.FieldIsDeleted,
		})
		_node.IsDeleted = value
	}
	if value, ok := ctc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: courseteacher.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := ctc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: courseteacher.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := ctc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: courseteacher.FieldDeletedAt,
		})
		_node.DeletedAt = value
	}
	if nodes := ctc.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   courseteacher.CourseTable,
			Columns: []string{courseteacher.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: course.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CourseTeacherCreateBulk is the builder for creating many CourseTeacher entities in bulk.
type CourseTeacherCreateBulk struct {
	config
	builders []*CourseTeacherCreate
}

// Save creates the CourseTeacher entities in the database.
func (ctcb *CourseTeacherCreateBulk) Save(ctx context.Context) ([]*CourseTeacher, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ctcb.builders))
	nodes := make([]*CourseTeacher, len(ctcb.builders))
	mutators := make([]Mutator, len(ctcb.builders))
	for i := range ctcb.builders {
		func(i int, root context.Context) {
			builder := ctcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CourseTeacherMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ctcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ctcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ctcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ctcb *CourseTeacherCreateBulk) SaveX(ctx context.Context) []*CourseTeacher {
	v, err := ctcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ctcb *CourseTeacherCreateBulk) Exec(ctx context.Context) error {
	_, err := ctcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ctcb *CourseTeacherCreateBulk) ExecX(ctx context.Context) {
	if err := ctcb.Exec(ctx); err != nil {
		panic(err)
	}
}
