// Code generated by ent, DO NOT EDIT.

package ent

import (
	"online-teaching/internal/ent/course"
	"online-teaching/internal/ent/coursechapter"
	"online-teaching/internal/ent/courseinfo"
	"online-teaching/internal/ent/coursesection"
	"online-teaching/internal/ent/courseteacher"
	"online-teaching/internal/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	courseFields := schema.Course{}.Fields()
	_ = courseFields
	// courseDescName is the schema descriptor for name field.
	courseDescName := courseFields[0].Descriptor()
	// course.NameValidator is a validator for the "name" field. It is called by the builders before save.
	course.NameValidator = courseDescName.Validators[0].(func(string) error)
	// courseDescIsDeleted is the schema descriptor for is_deleted field.
	courseDescIsDeleted := courseFields[3].Descriptor()
	// course.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	course.DefaultIsDeleted = courseDescIsDeleted.Default.(bool)
	// courseDescCreatedAt is the schema descriptor for created_at field.
	courseDescCreatedAt := courseFields[4].Descriptor()
	// course.DefaultCreatedAt holds the default value on creation for the created_at field.
	course.DefaultCreatedAt = courseDescCreatedAt.Default.(func() time.Time)
	// courseDescUpdatedAt is the schema descriptor for updated_at field.
	courseDescUpdatedAt := courseFields[5].Descriptor()
	// course.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	course.DefaultUpdatedAt = courseDescUpdatedAt.Default.(func() time.Time)
	// course.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	course.UpdateDefaultUpdatedAt = courseDescUpdatedAt.UpdateDefault.(func() time.Time)
	coursechapterFields := schema.CourseChapter{}.Fields()
	_ = coursechapterFields
	// coursechapterDescTitle is the schema descriptor for title field.
	coursechapterDescTitle := coursechapterFields[0].Descriptor()
	// coursechapter.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	coursechapter.TitleValidator = coursechapterDescTitle.Validators[0].(func(string) error)
	// coursechapterDescIsDeleted is the schema descriptor for is_deleted field.
	coursechapterDescIsDeleted := coursechapterFields[1].Descriptor()
	// coursechapter.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	coursechapter.DefaultIsDeleted = coursechapterDescIsDeleted.Default.(bool)
	// coursechapterDescCreatedAt is the schema descriptor for created_at field.
	coursechapterDescCreatedAt := coursechapterFields[2].Descriptor()
	// coursechapter.DefaultCreatedAt holds the default value on creation for the created_at field.
	coursechapter.DefaultCreatedAt = coursechapterDescCreatedAt.Default.(func() time.Time)
	// coursechapterDescUpdatedAt is the schema descriptor for updated_at field.
	coursechapterDescUpdatedAt := coursechapterFields[3].Descriptor()
	// coursechapter.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	coursechapter.DefaultUpdatedAt = coursechapterDescUpdatedAt.Default.(func() time.Time)
	// coursechapter.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	coursechapter.UpdateDefaultUpdatedAt = coursechapterDescUpdatedAt.UpdateDefault.(func() time.Time)
	courseinfoFields := schema.CourseInfo{}.Fields()
	_ = courseinfoFields
	// courseinfoDescDetail is the schema descriptor for detail field.
	courseinfoDescDetail := courseinfoFields[5].Descriptor()
	// courseinfo.DefaultDetail holds the default value on creation for the detail field.
	courseinfo.DefaultDetail = courseinfoDescDetail.Default.(string)
	// courseinfoDescState is the schema descriptor for state field.
	courseinfoDescState := courseinfoFields[6].Descriptor()
	// courseinfo.DefaultState holds the default value on creation for the state field.
	courseinfo.DefaultState = courseinfoDescState.Default.(string)
	// courseinfoDescIsDeleted is the schema descriptor for is_deleted field.
	courseinfoDescIsDeleted := courseinfoFields[7].Descriptor()
	// courseinfo.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	courseinfo.DefaultIsDeleted = courseinfoDescIsDeleted.Default.(bool)
	// courseinfoDescCreatedAt is the schema descriptor for created_at field.
	courseinfoDescCreatedAt := courseinfoFields[8].Descriptor()
	// courseinfo.DefaultCreatedAt holds the default value on creation for the created_at field.
	courseinfo.DefaultCreatedAt = courseinfoDescCreatedAt.Default.(func() time.Time)
	// courseinfoDescUpdatedAt is the schema descriptor for updated_at field.
	courseinfoDescUpdatedAt := courseinfoFields[9].Descriptor()
	// courseinfo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	courseinfo.DefaultUpdatedAt = courseinfoDescUpdatedAt.Default.(func() time.Time)
	// courseinfo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	courseinfo.UpdateDefaultUpdatedAt = courseinfoDescUpdatedAt.UpdateDefault.(func() time.Time)
	coursesectionFields := schema.CourseSection{}.Fields()
	_ = coursesectionFields
	// coursesectionDescTitle is the schema descriptor for title field.
	coursesectionDescTitle := coursesectionFields[0].Descriptor()
	// coursesection.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	coursesection.TitleValidator = coursesectionDescTitle.Validators[0].(func(string) error)
	// coursesectionDescType is the schema descriptor for type field.
	coursesectionDescType := coursesectionFields[1].Descriptor()
	// coursesection.DefaultType holds the default value on creation for the type field.
	coursesection.DefaultType = coursesectionDescType.Default.(string)
	// coursesectionDescIsDeleted is the schema descriptor for is_deleted field.
	coursesectionDescIsDeleted := coursesectionFields[3].Descriptor()
	// coursesection.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	coursesection.DefaultIsDeleted = coursesectionDescIsDeleted.Default.(bool)
	// coursesectionDescCreatedAt is the schema descriptor for created_at field.
	coursesectionDescCreatedAt := coursesectionFields[4].Descriptor()
	// coursesection.DefaultCreatedAt holds the default value on creation for the created_at field.
	coursesection.DefaultCreatedAt = coursesectionDescCreatedAt.Default.(func() time.Time)
	// coursesectionDescUpdatedAt is the schema descriptor for updated_at field.
	coursesectionDescUpdatedAt := coursesectionFields[5].Descriptor()
	// coursesection.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	coursesection.DefaultUpdatedAt = coursesectionDescUpdatedAt.Default.(func() time.Time)
	// coursesection.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	coursesection.UpdateDefaultUpdatedAt = coursesectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	courseteacherFields := schema.CourseTeacher{}.Fields()
	_ = courseteacherFields
	// courseteacherDescName is the schema descriptor for name field.
	courseteacherDescName := courseteacherFields[0].Descriptor()
	// courseteacher.NameValidator is a validator for the "name" field. It is called by the builders before save.
	courseteacher.NameValidator = courseteacherDescName.Validators[0].(func(string) error)
	// courseteacherDescIsDeleted is the schema descriptor for is_deleted field.
	courseteacherDescIsDeleted := courseteacherFields[4].Descriptor()
	// courseteacher.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	courseteacher.DefaultIsDeleted = courseteacherDescIsDeleted.Default.(bool)
	// courseteacherDescCreatedAt is the schema descriptor for created_at field.
	courseteacherDescCreatedAt := courseteacherFields[5].Descriptor()
	// courseteacher.DefaultCreatedAt holds the default value on creation for the created_at field.
	courseteacher.DefaultCreatedAt = courseteacherDescCreatedAt.Default.(func() time.Time)
	// courseteacherDescUpdatedAt is the schema descriptor for updated_at field.
	courseteacherDescUpdatedAt := courseteacherFields[6].Descriptor()
	// courseteacher.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	courseteacher.DefaultUpdatedAt = courseteacherDescUpdatedAt.Default.(func() time.Time)
	// courseteacher.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	courseteacher.UpdateDefaultUpdatedAt = courseteacherDescUpdatedAt.UpdateDefault.(func() time.Time)
}
