// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// CourseChapter is the predicate function for coursechapter builders.
type CourseChapter func(*sql.Selector)

// CourseComment is the predicate function for coursecomment builders.
type CourseComment func(*sql.Selector)

// CourseInfo is the predicate function for courseinfo builders.
type CourseInfo func(*sql.Selector)

// CourseSection is the predicate function for coursesection builders.
type CourseSection func(*sql.Selector)

// CourseSwiper is the predicate function for courseswiper builders.
type CourseSwiper func(*sql.Selector)

// Teacher is the predicate function for teacher builders.
type Teacher func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
