// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"online-teaching/internal/biz"
	"online-teaching/internal/conf"
	"online-teaching/internal/data"
	"online-teaching/internal/server"
	"online-teaching/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	courseRepo := data.NewCourseRepo(dataData, logger)
	courseUsecase := biz.NewCourseUsecase(courseRepo, logger)
	courseService := service.NewCourseService(courseUsecase)
	grpcServer := server.NewGRPCServer(confServer, courseService, logger)
	httpServer := server.NewHTTPServer(confServer, courseService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
